name: Build

on:
  push:
  pull_request:

jobs:
  assemble:
    name: Assemble
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build with Gradle
        run: ./gradlew assembleRelease
        # Upload all build artifacts in separate steps. This can be shortened once https://github.com/actions/upload-artifact/pull/354 is merged.
      - name: Upload artifact phone-libre-arm64-v8a-release-unsigned.apk
        uses: actions/upload-artifact@v4
        with:
          name: phone-libre-arm64-v8a-release-unsigned.apk
          path: ./app/phone/build/outputs/apk/libre/release/phone-libre-arm64-v8a-release-unsigned.apk
      - name: Upload artifact phone-libre-armeabi-v7a-release-unsigned.apk
        uses: actions/upload-artifact@v4
        with:
          name: phone-libre-armeabi-v7a-release-unsigned.apk
          path: ./app/phone/build/outputs/apk/libre/release/phone-libre-armeabi-v7a-release-unsigned.apk
      - name: Upload artifact phone-libre-x86_64-release-unsigned.apk
        uses: actions/upload-artifact@v4
        with:
          name: phone-libre-x86_64-release-unsigned.apk
          path: ./app/phone/build/outputs/apk/libre/release/phone-libre-x86_64-release-unsigned.apk
      - name: Upload artifact phone-libre-x86-release-unsigned.apk
        uses: actions/upload-artifact@v4
        with:
          name: phone-libre-x86-release-unsigned.apk
          path: ./app/phone/build/outputs/apk/libre/release/phone-libre-x86-release-unsigned.apk
      - name: Upload artifact tv-libre-arm64-v8a-release-unsigned.apk
        uses: actions/upload-artifact@v4
        with:
          name: tv-libre-arm64-v8a-release-unsigned.apk
          path: ./app/tv/build/outputs/apk/libre/release/tv-libre-arm64-v8a-release-unsigned.apk
      - name: Upload artifact tv-libre-armeabi-v7a-release-unsigned.apk
        uses: actions/upload-artifact@v4
        with:
          name: tv-libre-armeabi-v7a-release-unsigned.apk
          path: ./app/tv/build/outputs/apk/libre/release/tv-libre-armeabi-v7a-release-unsigned.apk
      - name: Upload artifact tv-libre-x86_64-release-unsigned.apk
        uses: actions/upload-artifact@v4
        with:
          name: tv-libre-x86_64-release-unsigned.apk
          path: ./app/tv/build/outputs/apk/libre/release/tv-libre-x86_64-release-unsigned.apk
      - name: Upload artifact tv-libre-x86-release-unsigned.apk
        uses: actions/upload-artifact@v4
        with:
          name: tv-libre-x86-release-unsigned.apk
          path: ./app/tv/build/outputs/apk/libre/release/tv-libre-x86-release-unsigned.apk

